spring.application.name=BookNest

server.port=9000
#DB config

spring.datasource.url=jdbc:postgresql://localhost:5432/bookNest
spring.datasource.username=postgres
spring.datasource.password=437528
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true